name: PlayerStats
version: '${version}'
main: fr.flonono.playerstats.PlayerStats
api-version: '1.20'
depend:
  - "PlaceholderAPI"
softdepend:
  - "LuckPerms"
commands:
  stats:
    description: Base command for the plugin
permissions:
  playerstats.seen:
    description: Allows one to see other people's stats
  playerstats.reset:
    description: Allows one to reset someone's stats
    default: op
  playerstats.reload:
    description: Allows one to reload plugin's config
    default: op
  playerstats.give:
    description: Allows one to give kills/deaths to a specified player
    default: op

